kind: Deployment
apiVersion: apps/v1 
metadata:
  name: dietpred
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dietpred
  template:
    metadata:
      labels:
        app: dietpred
    spec:
      containers:
        - name: dietpred
          image: yanuragaj/dietpred:v4
