kind: Deployment
apiVersion: apps/v1 
metadata:
  name: nlpmodel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlpmodel
  template:
    metadata:
      labels:
        app: nlpmodel
    spec:
      containers:
        - name: nlpmodel
          image: yanuragaj/nlp:v2
