apiVersion: v1
kind: Service
metadata:
  name: nlpservice
  labels:
    app:  nlpservice
spec:
  selector:
    app: nlpmodel
  type: NodePort
  ports:
    - nodePort: 30001
      port: 1234
      targetPort: 1234
