apiVersion: v1
kind: Service
metadata:
  name: dietservice
  labels:
    app:  dietservice
spec:
  selector:
    app: dietpred
  type: NodePort
  ports:
    - nodePort: 30000
      port: 80
      targetPort: 80
